baseurl = "https://dscinberlin.de/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "DSC Berlin"
title = "Developer Student Club Berlin"
disqusshortname = ""
pluralizelisttitles = false
DefaultContentLanguage = "en"

[menu]
  # [[menu.main]]
  #   identifier = "Blog"
  #   name = "Blog"
  #   url = "/blog/"
  #   weight = -120

  # [[menu.main]]
  #   identifier = "Events"
  #   name = "Events"
  #   url = "/events/"
  #   weight = -110

  [[menu.main]]
    identifier = "CoC"
    name = "Code of Conduct"
    url = "/coc"
    weight = -100

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
timeform = "15:04 Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Website and Blog of the Berlin local DSC group"
copyright = "Copyright © 2019 DSC Berlin"
logofile = "img/logo_color.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
enlarged = true
github = "dscinberlin"
email = "admin@dscinberlin.de"
# linkedin = "john-example-aa80ue8è"
# twitter = "example"
telegram = "https://t.me/dsc_berlin"
social_banner = "img/banner.png"
posts_navigation = false
small_banner_logo = false
attributions = [
  "Icon made by Freepik from www.flaticon.com",
]
titlestyle = "capitalize"
  [params.eventbanner]
  link = ""
  text = ""

[languages]
  [languages.en]
  languageName = "English"

  [languages.de]
  languageName = "German"
    [languages.de.params]
    description = "Website und Blog der lokalen Berliner DSC Gruppe"
